### PR TITLE
Disable flakey tests

### PR DESCRIPTION
**Pull request by bfirsh**
... to make the build work. @jonathan-s feel free to actually fix properly. ;)

### CODE REVIEW

**Comment by jonathan-s** [comment]
I'll leave this PR open for the time being. I'll eventually come to this.

**Comment by bfirsh** [comment]
@jonathan-s Would you be open to this, just to get things like security patches passing? (See current PRs!)

**Comment by bfirsh** [comment]
also ping @jessykate? these broken tests are blocking all other PRs...

**Comment by bfirsh** [comment]
Superceded by #588

**Pull request closed without merging**
