### PR TITLE
Fix thumbnails on S3

### LINKED ISSUE #462: Fix profile thumbnails on S3
They don't work because it assumes the files are on disk.

We should use https://github.com/matthewwithanm/django-imagekit instead.

Future bit of work: delete all the old thumbnails. See #437

### LINKED ISSUE #473: Image upload on registration page causes RequestDataTooBig errors
The cropper on the registration/profile edit page sets image data as a hidden form field instead of using a file field. This means Django doesn't recognise it as a file upload, so doesn't stream it to disk. It hits `DATA_UPLOAD_MAX_MEMORY_SIZE` to stop it loading loads of data into memory, as it should.

A couple of options:
1. Scrap the cropper and just do normal file uploads. I'm sure people know how to crop images if they need to. (+1 from me)
2. Refactor the cropper to use a file field.

### PR DESCRIPTION
**Pull request by bfirsh**
@jessykate Despite me saying the other day that I didn't need to touch the cropper, I have removed the cropper. Unfortunately it is fundamentally broken, and there is no easy fix (see #473).

At least for now to get this working, I figure people can crop their own pictures. If they don't crop it themselves it will automatically slice up the image so it is square.

See commit messages for more deets.

Fixes #462 
Fixes #473

### CODE REVIEW

**Comment by bfirsh** [comment]
screenshot 2019-03-04 12 57 13

awwww yeaaahh

**Comment by jonathan-s** [comment]
@bfirsh Any thoughts on using cloudinary which would do resizing etc?

**Comment by bfirsh** [comment]
Maybe? But why?

The django media/storages setup works, and it would require a lot of refactoring to switch to something else. So, let's perhaps defer thinking about that to the future.

**Comment by jonathan-s** [comment]
@bfirsh I remember @jessykate mentioning that they were using PIL to resize uploaded images and it introduced some complexities. Ie if someone uploads a 3mb image you wouldn't really want that to be loaded everytime a page is loaded. Cloudinary caches and resizes the image for you, so that's the primary use case. 

Not having to think about making the image a correct size might, or might not be worth it.

**Comment by bfirsh** [comment]
The thumbnails are generated at upload-time. That's what imagekit is doing for us.

**Comment by bfirsh** [comment]
@jessykate approved cropper killing on slack

**Comment by bfirsh** [comment]
Merging this myself so I test it on new production environment. Anyone feel free to do a post-merge review and we can fix in a follow-up. :)

**Pull request merged**
