### PR TITLE
Create location app and move one view

### PR DESCRIPTION
**Pull request by jonathan-s**
As per #349, this lays out the structure for the location app and moves one view to the new place. If it looks good so far. I'll refactor the view too and and a test to it :).

### CODE REVIEW

**Comment by bfirsh** [comment]
Ah - interesting! This is not actually the intention I had with #349. Perhaps I should have explained better.

I was suggesting we just move the existing apps we had into `modernomad/` without modification. So just as simple as moving:

- `core/` to `modernomad/core/`
- `bank/` to `modernomad/bank/`
- `gather/` to `modernomad/gather/`

... then rewriting any imports.

The question of whether it's a good idea to split out a big Django app into lots of individual ones is an interesting one. At a past job, we actually decided _against_ this, in favour of having one big monolithic app. The main reason being single, linear database migrations instead of a big mess of cross-app dependencies.

I don't have strong opinions, but I think we should at least a discussion to work out the benefits and disadvantages of refactoring our monolithic app into separate ones. It's a lot of work, and I think it's not clear whether it is good or bad.

So, perhaps refactoring the apps into separate apps is a different piece of work, and perhaps something that could be done after #349, to avoid muddling the two issues.

**Comment by bfirsh** [comment]
Some more thinking around this: https://medium.com/@DoorDash/tips-for-building-high-quality-django-apps-at-scale-a5a25917b2b5

**Comment by jonathan-s** [comment]
I can definitely see the point in having linear database migrations. Last october, me and James sat down and wrote down our thoughts here: https://docs.google.com/document/d/1lA8VNBbzqxOQ-JVUvOwHz4lI2FhRRHDrX_bUK_7LRcw/edit

Perhaps we can continue to have the discussion there, and you can add your thoughts there? We suggested a few apps there, but I think that perhaps there should be fewer than stated there. Ie booking and locations are pretty intimate with each other etc. 

The accounting part I think should be its own. 

So in terms of the advantages, I think the main advantage I'm seeing is that you get more clarity of where the code belongs, a step towards modularity. 

The main advantage of keeping everything together is easier migrations. Though in general, if you make sure to squash migrations as you go the criss-crossing of dependencies won't become much of an issue. It'll likely become an issue if you don't do that. 

I think either way there will be a lot of work, or do you forsee moving the models being particularly troublesome?

**Comment by jonathan-s** [comment]
@bfirsh Rebased again, do you have any more thoughts around this?

**Comment by jonathan-s** [comment]
@bfirsh, I changed the structure slightly so it's now directly under modernomad/core. That way it keeps the same structure as before. The only difference now is the namespacing, so I'd suggest that we move over one view after another, refactoring as we go and adding tests. 

That way everything gets a review without it being this massive block of code which gets somewhat unmanageable to review.

**Comment by jonathan-s** [comment]
This is now deprecated so closing this PR.

**Pull request closed without merging**
