### PR TITLE
Various factory enhancements

### PR DESCRIPTION
**Pull request by jessykate**
- Create an explicit known user with ID =1 that is also a superuser (`admin`/`password`)
- Add a known password `password` for all users
- Add user 1 as a location admin to all generated locations
- Add real timezones
- Add meaningful check in and check out times

### CODE REVIEW

**Comment by bfirsh** [comment]
Does this test failure not happen locally?

Currencies are created as part of the migrations (a project search will find the migration where they are created). Perhaps this is the reason they are colliding.

**Comment by jessykate** [comment]
gahhhhh you're right. i was just being lazy :see_no_evil: 

i think i'm confused though. if the `generate_test_data` management command (which is [called](https://github.com/embassynetwork/modernomad/blob/master/api/tests/commands/test_data_generation.py#L8) from the [erroring test](https://travis-ci.org/embassynetwork/modernomad/builds/484951887#L762) blows away the DB, then why would it generate a collision? 

separately, i agree that it would be nice to get that DRFT creation statement out of the migration. we could probably also address that when we squash migrations (#316).

**Comment by bfirsh** [comment]
@jessykate Yeah I have no idea why the error is happening. Does `./manage.py test` work locally? That's the only thing the tests are running. It runs on a fresh DB locally too, so it should be exactly what is happening on Travis.

**Comment by jessykate** [comment]
yeah interestingly it doesn't happen when i run `sudo docker-compose run web ./manage.py test` :anguished: 

i can look into it this weekend.

**Comment by bfirsh** [comment]
Pushed a fix!

[The `get_or_create` was done inline in the factory definition](https://github.com/embassynetwork/modernomad/blob/e024ec3a9027da66c88d2ac735a24fbb9eedbdd5/core/factory_apps/accounts.py#L22) which was actually executing the query at import time, when the factory class was being interpreted, instead of when the factory was being created.

The integrity error was weird, because `get_or_create` is used everywhere. I think the only explanation is was that it was a race condition, so two currencies were being created simultaneously between the get and create bits of `get_or_create`... 😬

Anyway... it's working now I think...

**Comment by jessykate** [comment]
it works for me! though that doesn't say much since i wasn't seeing an error before... but... i say ship it :)

**Pull request merged**
