### PR TITLE
Pull out functions so they can be run with a scheduler

### LINKED ISSUE #326: Should we replace Celery with Heroku scheduler?
Celery is only used to run scheduled tasks (sending emails, etc) and is not used to run any background tasks.

[Now we are moving to Heroku](https://github.com/embassynetwork/modernomad/issues/324), we could use the Heroku Scheduler to run these tasks instead of Celery.

Advantages:
- Cheaper (permanent celery dyno is $25/mo, scheduler will cost pennies)
- We don't have to upgrade Celery to 4.x (currently uses Celery 3 which doesn't work with Django 1.11)
- Less complexity (Celery has a lot of moving parts and breaks)

Disadvantages:
- Means we would have to add back Celery in the future if we want to use it for anything (but it's not even working at the moment so that doesn't seem like much extra work...)
- A little bit of work to migrate the Celery tasks to management commands
- Ties us to Heroku?
- Scheduler commands are configured in the web UI instead of being committed to repo, which is annoying

### PR DESCRIPTION
**Pull request by jonathan-s**
@jessykate, So... we now got a management command that can run all the tasks. All of these tasks except for backup seems to be related to email sendouts. 

As mentioned in #326, heroku scheduler is not precise and may also miss a scheduled appointment. But may still be good enough for what we need.  

> Scheduler job execution is expected but not guaranteed. Scheduler is known to occasionally (but rarely) miss the execution of scheduled jobs. If scheduled jobs are a critical component of your application, it is recommended to run a custom clock process instead for more reliability, control, and visibility. (https://devcenter.heroku.com/articles/scheduler)

The other issue that I see right now. It seems like every time any of these functions run it would send out an email. So there is no knowledge of whether an email has been sent out to the user or not. Correct me if I'm wrong here. 

Merging this PR should fix #326.

### CODE REVIEW

**Comment by jessykate** [comment]
woo! awesome!!

> ...but may still be good enough for what we need. 

my guess is it probably is... but we could try it, and then if we want to, add in a database field to track whether the messages have been sent? mailgun returns info on success/failure. we could use that to build a simple retry mechanism... 

> The other issue that I see right now. It seems like every time any of these functions run it would send out an email. So there is no knowledge of whether an email has been sent out to the user or not. Correct me if I'm wrong here.

ahh... do you mean that we actually might not have a good way to validate whether messages have already been sent?

**Comment by jonathan-s** [comment]
Perhaps we could hash the contents of the email, store it in a table. Before an email is being sent check that the hash doesn't exist for that user.

**Comment by bfirsh** [comment]
I think `crontab(hour=5, minute=30)` means run once per day at 05:30.

In my experience Heroku scheduling has been rock solid reliable. If we realy, really care about delivery, we could track it in the database so it is idempotent and run the scheduled task several times a night, that seems like massive overkil.

**Comment by bfirsh** [comment]
Also, LGTM! ✨

**Pull request merged**
