### PR TITLE
Add basic Docker setup

### PR DESCRIPTION
**Pull request by halfspiral**
Braindead simple way of doing a Docker + Docker Compose setup with modernomad. The user still has to create their own local_settings.py and set up their Django superuser. I have provided local_settings.docker.py as an example config for Docker usage. Simple instructions for use, after installing Docker and Docker Compose:

``` sh
git clone https://github.com/halfspiral/modernomad -b docker
cd modernomad
cp modernomad/local_settings.docker.py modernomad/local_settings.py
vim modernomad/local_settings.py  # add your config settings here
docker-compose up -d              # app is now available at localhost:8000
docker exec -it modernomad_web_1 python manage.py createsuperuser
```

To rebuild the app after config or code changes:

```
docker-compose up -d --build web
```

To change what port is used or where the volumes are mounted, it is suggested to edit the docker-compose.yml file:

``` yaml
    ports:
      - '8000:8000'                              # change to '80:8000' to use port 80
    volumes:
      - /var/lib/modernomad:/var/lib/modernomad  # change me too if you want
```

None of this documentation is included in any files in the PR. Perhaps it should be?

### CODE REVIEW

**Comment by jessykate** [comment]
HI @halfspiral! Thanks! I haven't used docker before but a few people are using vagrant. 

Maybe the documentation could go into the docs linked to from readme file? 

Are you trying to get this running as-is or are you thinking of doing some development work on it? Would love to hear about your use cases.

**Comment by halfspiral** [comment]
Hi @jessykate, thanks for the reply! I'm interested in contributing a few bug fixes and feature additions to Modernomad. I've gotten the application running as-is and I think it's pretty awesome. I'm currently experimenting with a new production environment with all my applications running in Docker.

The Docker setup in this PR is actually not very convenient to use during dev/test cycles because the user has to rebuild the container every time there are any changes to the code or the configuration. There are ways to set up the Docker containers so that this is less painful, but in my opinion it's a lot better to use Vagrant during development.

Does it make sense to make a new file for this, i.e. docker-setup.md? I also noticed there is no documentation on how to use Vagrant, so maybe it makes sense to add a little section about that to the readme as well? Let me know and I can update this PR.

**Comment by kgstew** [comment]
Hi @halfspiral, Glad your digging in!

I've been working on some upgrades to the Vagrant config and adding new info to the wiki. If you want to give it a shot and help me with testing you could checkout the `vagrant_upgrade branch and try to follow the instructions here https://github.com/embassynetwork/modernomad/wiki/Vagrant-Install-and-Config

@jessykate is the one to talk to about new features and bugs. 

Happy to have your help!

**Comment by jessykate** [comment]
@halfspiral sweet! a docker-setup.md sounds great. just to clarify, this should have no effect for those who are _not_ using docker, right? it will just enable you those who wish to use docker to do so?

**Comment by jessykate** [comment]
@halfspiral are there any particular areas you'd like to dig into? happy to give context on how ideas you have could fit into what we're working on at the moment.

**Comment by gardner** [comment]
this is cool @halfspiral can we use this to replace the crazy vagrantfile that we have?

**Pull request closed without merging**
