### PR TITLE
No more celery

### PR DESCRIPTION
**Pull request by bfirsh**

### CODE REVIEW

**Comment by jonathan-s** [comment]
@bfirsh If you rebase this against master I'll merge it, taking @jessykate silence as a yes :). Reason for rebasing is that it will downgrade lxml that we've upgraded earlier.

**Comment by bfirsh** [comment]
Ah - good catch. I did rebase, but I resolved the conflict incorrectly!

**Comment by bfirsh** [comment]
Fixed!

**Comment by jonathan-s** [comment]
🎉

**Comment by bfirsh** [comment]
Thanks!

**Pull request merged**
