### PR TITLE
Heroku scheduled tasks

### PR DESCRIPTION
**Pull request by bfirsh**
Part of moving scheduled tasks to Heroku in #323.

The meat of this pull request is ae86298 which moves the more generic scheduler command into a specific command that runs all the commands for a day. Each one doesn't need to be scheduled individually, so this vastly simplifies the cron config.

There are lots of other miscellaneous changes here. Mostly test data fixes and some logging changes.

### CODE REVIEW

**Comment by jonathan-s** [comment]
@bfirsh Looks like Cypress test failed. My hunch is that it's not running on a completely clean database where the test data is generated directly afterwards.

**Comment by bfirsh** [comment]
Oh! That's because I changed the factory. Annoyingly if you change anything in the factory, anything after that point changes. (The consistent random seed is one value further on, so it is all consistently different. 🙄 )

**Comment by bfirsh** [comment]
Or perhaps better... if a test depends on a particular bit of data existing (e.g. the name of a location) we specify it expllicity in the test instead of relying on the random data.

**Comment by bfirsh** [comment]
Filed here: https://github.com/embassynetwork/modernomad/issues/376

**Pull request merged**
